### ISSUE TITLE
Plugin no longer displaying on the website 

### ISSUE THREAD

**Issue by borisbobo69** [StartupsPoleEmploi/anotea#1117]
We currently use the anotea widget on ourwebsite https://cibformation.fr/ , and It has stopped displaying  correctly for a few weeks. We checked with our developer to try a troubleshooting. we have tried every possible solution and his conclusion is the following : "we need to regenerate code from their website". 

Any idea on why this is not displaying correctly ? 

Thank you in advance for your response.

screenshots of the widget
![widget anotea_dev](https://user-images.githubusercontent.com/71817740/94126891-7e6ef700-fe58-11ea-843e-1627c85b48b5.png)
![widget anotea_disp](https://user-images.githubusercontent.com/71817740/94126893-7fa02400-fe58-11ea-9afc-76f052a2d052.png)

**Comment by JulienPerrin** [comment]
Hi, thank you for oppening this issue. 
It works for me when I open this simple index.html file in Chrome with your SIRET : 

```html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
	<head>
		<title>Test</title>
		<script src="https://anotea.pole-emploi.fr/static/js/widget/anotea-widget-loader.min.js"></script>
	</head>
	<body style="margin: 0;" bgcolor="#e0e0e0">
		<div
			class="anotea-widget" 
			data-type="organisme"
			data-format="liste"
			data-identifiant="83127227300010"
			style="color: inherit;"
		></div>
	</body>
</html>
```

Did you add the script `<script src="https://anotea.pole-emploi.fr/static/js/widget/anotea-widget-loader.min.js"></script>` in your webpage ? I can't find it.

**Comment by borisbobo69** [comment]
Hello Julien , 

Thank you for your quick response. Effectively we are missing the script in the header. The dev is working to implemen it now.Thank you very much for your time, in finding the missing element for this widget to work. We much appreciate it ! and hope that it will help others that face the same issue.

**Comment by JulienPerrin** [comment]
Happy to hear it. 👍
