### ISSUE TITLE
Appel double dans les stats ESD

### ISSUE THREAD

**Issue by tyjak** [StartupsPoleEmploi/anotea#1134]
@JulienPerrin des logs qui ne devraient pas être remontés continuent à l'être... J'ai un peu fouillé pour comprendre ce qui se passe...

Cet appel provenant d'un js, ne devrait pas être logué pour l'ESD, il est compté comme un appel API alors qu'il s'agit du widget : 
https://github.com/StartupsPoleEmploi/anotea/blob/ab37763b2ab75d66d874869c51d6960617b930ea/backend/src/http/site/static/js/widget/anotea-widget-loader.js#L47

Lors de l'appel du widget 2 appels sont logués :
1. premier appel pour obtenir le script js ce qui appel une première fois l'API, voir lien ci-dessus
2. deuxième appel par le script js, appel légitime et bien comptabilisé comme widget

Une solution :
Modifier la fonction
https://github.com/StartupsPoleEmploi/anotea/blob/ab37763b2ab75d66d874869c51d6960617b930ea/backend/src/http/site/static/js/widget/anotea-widget-loader.js#L40

en ajouter un param dans le header ou un param GET pour pouvoir repérer cette requête à ne pas loger dans : https://github.com/StartupsPoleEmploi/anotea/blob/4bb9d02154d02aabaa595bfa2a32d8f065161e8e/backend/src/http/utils/middlewares/createDatalakeExporter.js#L30

**Comment by JulienPerrin** [comment]
Effectivement, on ne sait pas que l'appel vient du Widget dans ce cas-là. Je vais regarder pour ajouter le header qui va bien pour qu'on sache que l'appel vient du widget.

**Comment by JulienPerrin** [comment]
C'est corrigé, l'info comme quoi l'appel vient du widget est maintenant bien transmise, je viens de tester en prod sur LBF.

**Comment by JulienPerrin** [comment]
Je retire ce que j'ai dit, je me prend cette erreur sur LBF : 

`Request header field x-anotea-widget is not allowed by Access-Control-Allow-Headers in preflight response.`

**Comment by tyjak** [comment]
Du coup est-ce qu'il est possible de passer l'info dans un paramètre GET lors de l'appel fait par le js ?

**Comment by JulienPerrin** [comment]
Je vais regarder ce que je peux faire.

**Comment by JulienPerrin** [comment]
C'est corrigé, je livrerai en prod lundi.

**Comment by JulienPerrin** [comment]
Je viens de livrer à l'instant. J'ai testé sur LBF plus d'erreur dans les appels. 
Je pense que c'est bon. 
Il devrait encore y avoir des doublons dans les logs exportés ce soir mais plus demain.
