### ISSUE TITLE
Paramètre sur le widget pour affichage à vide

### ISSUE THREAD

**Issue by DuaelFr** [StartupsPoleEmploi/anotea#846]
Ce serait vraiment pratique de pouvoir forcer le widget à s'afficher même s'il n'y a pas de résultats. Cela éviterait à certains designs d'être dégradés dans ce genre de cas.

Chaque format pourrait réagir différemment. Proposition ci-dessous : 

![Sélection_009](https://user-images.githubusercontent.com/370584/65054940-a9358e00-d96e-11e9-824c-178675d44b9f.png)
![Sélection_008](https://user-images.githubusercontent.com/370584/65054945-aaff5180-d96e-11e9-8c13-7640c258bab3.png)
![Sélection_010](https://user-images.githubusercontent.com/370584/65054949-ad61ab80-d96e-11e9-9d71-c9d13e0cbf42.png)

**Comment by bguerout** [comment]
Merci pour la suggestion.
Effectivement c'est un choix qu'on a fait dans le widget.
Mais on pourrait imaginer un affichage spécifique quand il n'y a pas d'avis (ex: Nous n'avons pas encore récolté d'avis pour cette formation...).
Nous allons étudier la faisabilité.

**Comment by DuaelFr** [comment]
Si j'avais pas un projet à finir je vous aurais fait une PR :disappointed:

**Comment by JulienPerrin** [comment]
Bonjour @DuaelFr, 

La fonctionnalité demandée a finalement été mise en place sur Anotéa. 
Pour voir ce que ça donne, vous pouvez aller sur cette page : https://anotea.pole-emploi.fr/doc/widget, rubrique 
> Exemple d'une formation sans avis avec show-if-0-reviews à true

Pour faire marcher la fonctionnalité, il suffit de renseigner dans le div le paramètre `show-if-0-reviews` à `true`, par défaut il vaut `false`. 
Je vous laisse fermer l'issue si vous considérez le problème résolu.

**Comment by DuaelFr** [comment]
Merci ça a l'air top !
Je ne travaille plus sur le projet pour lequel nous avion échangé mais votre démo est éloquente.
Bien joué !
